name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '28 16 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has been marked stale'
        stale-pr-message: 'This pull request has been marked stale .'
        stale-issue-label: 'no-issue-activity-detected'
        stale-pr-label: 'no-pr-activity-detected'
